#pragma config(Sensor, S2,     LeftColor,      sensorEV3_Color)
#pragma config(Sensor, S3,     RightColor,     sensorEV3_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void armconfig()
{
setMotorTarget(motorA, 200, 20);
sleep(3000);
resetMotorEncoder(motorA);
}

void armdown()
{
resetMotorEncoder(motorA);
setMotorTarget(motorA, -150, 20);
waitUntilMotorStop(motorA);
sleep(200);
}
void armup()
{
resetMotorEncoder(motorA);
setMotorTarget(motorA, 150, 20);
waitUntilMotorStop(motorA);
sleep(200);
}
void Turnleft()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, -30, 35);
setMotorTarget(motorB, -30, 35);
waitUntilMotorStop(motorC);
sleep(200);
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, 135, 35);
setMotorTarget(motorB, -135, 35);
waitUntilMotorStop(motorC);
sleep(200);
}
void TurnRight()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, -135, 35);
setMotorTarget(motorB, 135, 35);
waitUntilMotorStop(motorC);
sleep(200);
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, 30, 35);
setMotorTarget(motorB, 30, 35);
waitUntilMotorStop(motorC);
sleep(200);
}
void cargobelt()
{
motor[motorB]=0;
motor[motorC]=0;
sleep(200);
armdown();
sleep(200);
TurnRight();
sleep(200);
armup();
Turnleft();
}
task main()
{
armconfig();
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
repeat(forever)
	{
		if(SensorValue[S4]>4)
		{
			motor[motorB]=15;
			motor[motorC]=15;
		}
		else if(SensorValue[S4]<4)
		{
		cargobelt();
		}
		else
		{
		sleep(200);
		}
	}
}
