#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);

setMotorTarget(motorB, 1000, 50);
setMotorTarget(motorC, 1000, 50);

resetMotorEncoder(motorA);

waitUntilMotorStop(motorA);
waitUntilMotorStop(motorB);
sleep(200);
setMotorTarget(motorA, -170, 50);
sleep(2000);
setMotorTarget(motorB, -1000, 50);
setMotorTarget(motorC, -1000, 50);
waitUntilMotorStop(motorB);

sleep(200);


}
