#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 void turnstationary()
{
setMotorTarget(motorB, 470, 30);
setMotorTarget(motorC, 100, 7);
waitUntilMotorStop(motorB);
waitUntilMotorStop(motorC);
}

void resetmotor()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
}

void moveforward()
{
setMotorTarget(motorB, 1100, 50);
setMotorTarget(motorC, 1100, 50);
waitUntilMotorStop(motorC);
}
task main()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
moveforward();
sleep(200);
resetmotor();
turnstationary();

resetmotor();
moveforward();
sleep(200);
resetmotor();
turnstationary();

resetmotor();
moveforward();
sleep(200);
resetmotor();
}
