#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

 void turnstationary()
{
setMotorTarget(motorB, 170, 30);
setMotorTarget(motorC, -170, 30);
waitUntilMotorStop(motorB);
}

void resetmotor()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
}

void moveforward()
{
setMotorTarget(motorB, 1200, 50);
setMotorTarget(motorC, 1200, 50);
waitUntilMotorStop(motorC);
}
task main()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
moveforward();
sleep(200);
resetmotor();

turnstationary();
sleep(200);
resetmotor();
moveforward();
sleep(200);
resetmotor();

turnstationary();
sleep(200);
resetmotor();
moveforward();
sleep(200);
}
