#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//displayBigTextLine(2, "Line 1: %dcm", distanceLine1);
int lineNum = 1;//Which line its on (Used for logic to determine which line it has to go to)
int distance4Line

float convertDegToCM(int encoderNum){
	return (encoderNum / 360.0)*(5.6 * PI);
}

void rsMotors(){//Reset Motor Encoders
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
sleep(200);
}

void uTurn(){//turn Around
/*

			*crickets*

*/
}

void forward(){//Moves forward on a condition until it sees black
motor[motorB] = 15;
motor[motorC] = 15;
sleep(200);
}
void STP(){//stop
motor[motorB] = 0;
motor[motorC] = 0;
sleep(200);
}
task main(){
rsMotors();
repeat(forever){

	if(getColorName(S3) == colorWhite){
		forward();
		}
	else{
		STP();
		if(lineNum == 1){

			}
		}
	}//forever
}
