#pragma config(Motor,  motorA,          arm,           tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorB,          right,         tmotorEV3_Large, PIDControl, driveRight, encoder)
#pragma config(Motor,  motorC,          left,          tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorD,          gear,          tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void armconfig()
{
setMotorTarget(motorA, 200, 20);
sleep(3000);
resetMotorEncoder(motorA);

}

void forward()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, 800, 15);
setMotorTarget(motorC, 800, 15);
waitUntilMotorStop(motorC);
sleep(200);
}

void backwards()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, -400, 15);
setMotorTarget(motorC, -400, 15);
waitUntilMotorStop(motorC);
sleep(200);
}

void spining()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, 1000, 15);
setMotorTarget(motorC, -1000, 15);
waitUntilMotorStop(motorC);
sleep(200);
}

task main()
{
sleep(2+000);
motor[motorD] = 30;
forward();
backwards();
motor[motorD] = 100;
sleep(200);
armconfig();
resetMotorEncoder(motorA);
setMotorTarget(motorA, -160, 50);
waitUntilMotorStop(motorA);
spining();
sleep(200);
forward();
sleep(200);
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorA, 0, 15);
setMotorTarget(motorC, 200, 30);
setMotorTarget(motorB, 100, 10);
waitUntilMotorStop(motorB);
sleep(200);
forward();
resetMotorEncoder(motorB);
setMotorTarget(motorB, -200, 30);
waitUntilMotorStop(motorB);
sleep(200);
motor[motorD] = 30;
forward();
sleep(200);
motor[motorD] = 0;
}
