#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//int distancewall = 32;//oh I can't possibly figure out what this variable does maybe like its in the name or something dunno....
int turn = 172.5;//Right/left point turn
int distancePerson = 53;//variable for detecting the human room
//bool emptyroomdone = false; //bad uneeded function
int SmTurn = 55;
void resetMTR(){
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	//resetMotorEncoder(motorA);//Dunno if this will cause problems in rescue room
}
void motorstop(){//it does  a thing
motor[motorB]=0;
motor[motorC]=0;
sleep(200);
}
void InclineRight(){
//turn slightly right
motorstop();
sleep(200);
resetMTR();
sleep(200);
setMotorTarget(motorB, SmTurn, 20);
setMotorTarget(motorC, -SmTurn, 20);
waitUntilMotorStop(motorB);
}
void InclineLeft(){
//turn slightly left
motorstop();
sleep(200);
resetMTR();
sleep(200);
setMotorTarget(motorB, -SmTurn, 20);
setMotorTarget(motorC, SmTurn, 20);
waitUntilMotorStop(motorB);
sleep(200);
}//not needed anymore and kinda broken (edit: not anymore nerd!)
void turnleft(){// yes
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, -turn, 15);
setMotorTarget(motorC, turn, 15);
waitUntilMotorStop(motorB);
}
void turnright(){// no
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, turn, 15);
setMotorTarget(motorC, -turn, 15);
waitUntilMotorStop(motorB);
}

void ripjakeEv3(){
//move forward
motor[motorB]=30;
motor[motorC]=30;
}
//(getColorName(S3)== colorRed)
void prgmforward(){
//move forward a very specific ammount (FOR RUBBLE ROOM)
resetMTR();
setMotorTarget(motorB, 1200, 30);
setMotorTarget(motorC, 1200, 30);
waitUntilMotorStop(motorB);
sleep(200);
}
void kidnap(){
//Rescue the human
resetMTR();
setMotorTarget(motorB, 600, 30);
setMotorTarget(motorC, 600, 30);
waitUntilMotorStop(motorB);
//move arm down
//moveforward until uh yes
motorstop();
motor[motorA] = -15;
sleep(3000);
motor[motorA] = 0;
motor[motorB] = 10;
motor[motorC] = 10;//move forward
while(SensorValue[S4] < distancePerson){//basically this is when the real stuff happens

	if((SensorValue[S4] < 11) && (SensorValue[S4] > 9)){//needs to be changed slightly
		motorstop();
		sleep(200);
		resetMotorEncoder(motorA);
		setMotorTarget(motorA, 80, 50);
		waitUntilMotorStop(motorA);
		resetMTR();
		//move slightly forward in order to be in the middle of the room
		int fwrd = 300;
		setMotorTarget(motorB, fwrd, 10);
		setMotorTarget(motorC, fwrd, 10);
		waitUntilMotorStop(motorB);
		sleep(200);
		turnleft();
		ripjakeEv3();
		sleep(6800);
		}//this is supposed to stop and then move the arm up to pick them up however rigiht now it just runs them over.
	}
}

/*void smallforward(){
//honestly I dont know what this does anymore //nvm it uh well moves forward a lil bit on the orange pad
int ammount = 400;
motorstop();
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, ammount, 20);
setMotorTarget(motorC, ammount, 20);
waitUntilMotorStop(motorB);
}
*/
void firefighter(){
	bool process = true;
	while((getColorName(S3) == colorYellow) && (process == true)){
		motorstop();
		setLEDColor(ledOrangeFlash);
		sleep(8000);
	}
	if((getColorName(S3) == colorWhite) && (process == true)){
		turnleft();
		sleep(300);
		ripjakeEv3();
		sleep(3000);
		process = false;
	}
}
//int Switcher = 0; no longer needed as function changed
void cartogrpahy(){//Empty room or firefighting room figure it out
	bool holdloop = true;
	ripjakeEv3();
	while(holdloop == true){
		if(SensorValue[S4] < 86){
			motorstop();
			if(getColorName(S3) == colorWhite){
				setLEDColor(ledOrange);
				sleep(200);
				turnleft();
				sleep(200);
				ripjakeEv3();
				sleep(2000);
				holdloop = false;
			}
			else if(getColorName(S3) == colorYellow){
				firefighter();
				sleep(200);
				holdloop = false;
			}
		}//epic this worked so well now just time to recreate it for rubble/rescue room
	}
}//void
void fbiscuit(){//rubble room funi haha inside joke lmao cope (hilarious trust)
motorstop();
sleep(200);
turnleft();
sleep(200);
prgmforward();
sleep(200);
turnright();
sleep(200);
prgmforward();
sleep(200);
turnleft();
sleep(600);
ripjakeEv3();
}

void surveyer(){//figure out difference between rescue room and rubble room
	motorstop();
	InclineLeft();
	bool holdloop = true;
	while(holdloop == true){
		sleep(200);
		/* Field data:
		Rescue room Sensor reads 125:
		Rubble Room sensor: 33
		MWHAHAHAHA very good difference should work well
		*/
		if((SensorValue[S4] < 127) && (SensorValue[S4] > 123)){//If true this is rescue room or it messed up somehow
			InclineRight();
			holdloop = false;
			sleep(500);
			kidnap();//rescue room code
			sleep(200);
			//holdloop = false;
		}
		if((SensorValue[S4] < 34) && (SensorValue[S4] > 32)){
			InclineRight();
			holdloop = false;
			sleep(200);
			fbiscuit();
			sleep(200);
			//holdloop = false;
		}
	}
}

task main()//it does a thing
{
	repeat(forever){
//note 1327 //what is this comment??? i forgor
		/*while(SensorValue[S4] > 86){
			ripjakeEv3();
			sleep(200);
		}//conflicts with other functions?*/

		if(SensorValue[S4] < 60){
			surveyer();
		}
		//replace this
		/*if(SensorValue[S4] < 40){//rubble room
			fbiscuit();
		}
		if((SensorValue[S4] < 60) && (SensorValue[S4] > 59)){//rescue room
			kidnap();
		}*/

		if((SensorValue[S4] > 147) && (SensorValue[S4] < 149)){//Empty Room / Fire room
			cartogrpahy();
		}
		else{//Move forward
		ripjakeEv3();
		sleep(200);
		}
//trash old code below dunno why its even still there tbh
//if have stuff
	//if doll
	//if rubble
//else
	//go foward
	//if yellow -> fire room
	//else -> leave

		/*
		if(getColorName(S3) == colorYellow){ //what is wrong with this
			smallforward();
			firefighter();
		}

		if((SensorValue[S4] > 81) && (SensorValue[S4] < 89) && (getColorName(S3) == colorWhite)){
			setLEDColor(ledOrange);
			motorstop();
			turnleft();
			sleep(200);
			ripjakeEv3();
			sleep(3000);
			//emptyroomdone = true;//bad solution (it just avoids the root problem)
		}*/
	}//forever
}//task main

/*
¦¯¦ ¦¦¦ _¯¦ ¦_¦¦ ¯¦¯ ¦¦¦ ¦¯_¯¦   ¦¦¦ _¯¦ ¦__ ¦¯   ¦ ¦_¦¦ ¦¯¯ ¦
¯¯¦ ¦_¦ ¦¯¦ ¦¦¯¦ ¦¦¦ ¦_¦ ¦¦¯¦¦   ¦__ ¦¯¦ ¦_¦ _¦   ¦ ¦¦¯¦ ¦__ _
*/ //rip 2020 dev team
