#pragma config(Sensor, S2,     ColorRight,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S3,     ColorRight,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void armconfig()
{
setMotorTarget(motorA, 200, 20);
sleep(3000);
resetMotorEncoder(motorA);
}

void armdown()
{
setMotorTarget(motorA, -150, 20);
waitUntilMotorStop(motorA);
sleep(200);
}
void armup()
{
setMotorTarget(motorA, 0, 20);
waitUntilMotorStop(motorA);
sleep(200);
}
void Turnleft()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, 50, 5);
setMotorTarget(motorB, -50, 5);
waitUntilMotorStop(motorC);
}
void TurnRight()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, -50, 5);
setMotorTarget(motorB, 50, 5);
waitUntilMotorStop(motorC);
}
task main()
{
armconfig();
int position;
position = 1;
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
repeat(forever)
	{
		if ((getColorName(S2)== colorWhite) && (getColorName(S3)== colorWhite))
		{
			motor[motorB]=15;
			motor[motorC]=15;
		}
		else if (getColorName(S2)== colorBlack)
		{
			motor[motorB]=0;
			motor[motorC]=0;
			Turnleft();
		}
		else if (getColorName(S3)== colorBlack)
		{
			motor[motorB]=0;
			motor[motorC]=0;
			TurnRight();
		}
		else if ((getColorName(S3)== colorRed) || (getColorName(S3)== colorRed))
		{
			if ((position)==1)
			{
				armdown();
				sleep(200);
			}
			else if ((position)==2)
			{
			motor[motorB]=0;
			motor[motorC]=0;
			armup();
			}
			else
			{
				sleep(200);
			}
		}
		else
		{
		sleep(200);
		}
	}
}
