#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void turnleft()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, 90, 7);
setMotorTarget(motorC, -90, 7);
waitUntilMotorStop(motorC);
}
void turnright()
{
setMotorTarget(motorB, -360, 7);
setMotorTarget(motorC, 360, 7);
waitUntilMotorStop(motorB);
waitUntilMotorStop(motorC);
}
void forward()
{
motor[motorB] = 30;
motor[motorC] = 30;
}
void motorstop()
{
motor[motorB] = 0;
motor[motorC] = 0;
sleep(200);
}

task main()
{
	while (SensorValue[S4] > 15)
		{
		forward();
		sleep(400);
		}
	while (SensorValue[S4] < 15)
		{
		motorstop();
		turnleft();
		sleep(2000);
		turnright();
		}
}
