#pragma config(Sensor, S1,     leftcolor,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     gyroSensor,     sensorEV3_Gyro, modeEV3Gyro_RateAndAngle)
#pragma config(Sensor, S3,     rightcolor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int distancewall = 15;

void InclineRight(){
//turn slightly right
}
void InclineLeft(){
//turn slightly left
}
void motorstop(){
//stops moving forward
}
void turnleft(){


}
void turnright(){

}

//(getColorName(S3)== colorRed)


task main()
{
	if(SensorValue[S4] > distancewall)
	//check if rubble or human with really jank solution
		InclineLeft();
		//now check again (if it is still detected then its a wall not a human)
			if(SensorValue[S4] < distancewall)
				//run rubble room code)
				InclineRight();
				turnleft();
				forward();
				if(SensorValue[S4] > distancewall)
				{
					motorstop();
					turnright();
					motorstop();
					//last turn is a bit tricky
					resetMotorEncoder(motorB);
					resetMotorEncoder(motorC);
					setMotorTarget(motorB, 50, 30);
					setMotorTarget(motorC, 50, 30);
					waitUntilMotorStop(motorB);
					turnleft();
				}
				else(){
					playSound(soundException);
				}
			}
			else(){
			//human rescue code
			}

	else if(getColorName(S1)== colorOrange)
	{

		motorstop();
		sleep(6000);

	}

}
