#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorC, -178, 5);
setMotorTarget(motorB, 178, 5);
waitUntilMotorStop(motorC);
waitUntilMotorStop(motorB);
sleep(500);
}
