#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int toMiddle = 1315;//DIstance to middle of the room
int PointTurn = 172.5;//value of for turning
int DisToRMStart = 2500;//Distance to MotorStart
int DfMtrSpeed = 30;//Default Motorspeed

void RSmotors(){//resets motors obviously
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	sleep(200);
}
void motorstop(){//it does  a thing
motor[motorB]=0;
motor[motorC]=0;
sleep(200);
}
void prgmforward(){
//move forward a very specific ammount (FOR RUBBLE ROOM)
RSmotors();
setMotorTarget(motorB, 1200, 30);
setMotorTarget(motorC, 1200, 30);
waitUntilMotorStop(motorB);
sleep(200);
}
void prgmforwardint(int x){
//move forward a very specific ammount (FOR RUBBLE ROOM)
RSmotors();
setMotorTarget(motorB, x, 30);
setMotorTarget(motorC, x, 30);
waitUntilMotorStop(motorB);
sleep(200);
}
void LeftTurn(){
RSmotors();
setMotorTarget(motorB, -PointTurn, DfMtrSpeed);
setMotorTarget(motorC, PointTurn, DfMtrSpeed);
waitUntilMotorStop(motorB);
sleep(200);
}
void RightTurn(){
RSmotors();
setMotorTarget(motorB, PointTurn, DfMtrSpeed);
setMotorTarget(motorC, -PointTurn, DfMtrSpeed);
waitUntilMotorStop(motorB);
sleep(200);
}

void NextRoom(){//go to the next room in a specific spot
	RSmotors();
	setMotorTarget(motorB, DisToRMStart, DfMtrSpeed);
	setMotorTarget(motorC, DisToRMStart, DfMtrSpeed);
	waitUntilMotorStop(motorB);
	sleep(200);
}
void GoToMiddle(){
	RSmotors();
	setMotorTarget(motorB, toMiddle, DfMtrSpeed);
	setMotorTarget(motorC, toMiddle, DfMtrSpeed);
	waitUntilMotorStop(motorB);
	sleep(200);
}

void fireroom(){
	while(getColorName(S3) == colorYellow){
		sleep(200);
	}
	prgmforwardint(300);
	sleep(200);
}
void emptyRoom(){
	GoToMiddle();
	sleep(200);
	if(getColorName(S3) == colorYellow){
	fireroom();
	}
	else{//actual empty room code
		setLEDColor(ledOrange);
	}
	LeftTurn();
	NextRoom();
}
void fbiscuit(){
motorstop();
sleep(200);
LeftTurn();
sleep(200);
prgmforward();
sleep(200);
RightTurn();
sleep(200);
prgmforwardint(1280);
sleep(200);
LeftTurn();
sleep(600);
motor[motorB] = 30;
motor[motorC] = 30;
}
void kidnap(){
int gettingCLoser = true;
while(gettingCLoser == true){
	motor[motorA] = -30;
	sleep(1000);
	motor[motorB] = 15;
	motor[motorC] = 15;
		if(SensorValue[S4] < 11){
			motor[motorB] = 0;
			motor[motorC] = 0;
			setMotorTarget(motorA, 80, 30);
			waitUntilMotorStop(motorA);
			sleep(200);
			RSmotors();
			setMotorTarget(motorB, 150, DfMtrSpeed);
			setMotorTarget(motorC, 150, DfMtrSpeed);
			waitUntilMotorStop(motorB);
			LeftTurn();
			NextRoom();
			gettingCLoser = false;
		}//Arm/Pickupq
	}
}
void stuff(){//theres stuff in the room
	if(SensorValue[S4] > 50){//rescue stuff I guess idk
		kidnap();
	}//Rescue room
	else{//Rubble room Code
		fbiscuit();
	}//rubble room
}//void
task main()
{
	//stuff();
	repeat(forever){
		if(SensorValue[S4] > 130){
			emptyRoom();
		}
		else{
		stuff();
		}
	}
}//task main
