#pragma config(StandardModel, "EV3_REMBOT")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat(forever){
		while(getColorName(S3)== colorRed){
			motor[motorB]=0;
			motor[motorC]=0;
		}
		motor[motorB]=30;
		motor[motorC]=30;
	}
}
