#pragma config(Sensor, S1,     touchSensor,    sensorEV3_Touch)
#pragma config(Sensor, S3,     colorSensor,    sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorA,          armMotor,      tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void turnleft()
{
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
	setMotorTarget(motorB, 170, 30);
	setMotorTarget(motorC, -170, 30);
	waitUntilMotorStop(motorC);
}

void forward()
{
	motor[motorB] = 50;
	motor[motorC] = 50;
}

void stopmotors()
{
	motor[motorB] = 0;
	motor[motorC] = 0;
}

void backup()
{
resetMotorEncoder(motorB);
resetMotorEncoder(motorC);
setMotorTarget(motorB, -150, 30);
setMotorTarget(motorB, -150, 30);
waitUntilMotorStop(motorC);
}
task main()
{
	repeat(4)
	{
		while (SensorValue[touchSensor]==0)
		{
			forward();
		}
		while (SensorValue[touchSensor]==1)
		{
			stopmotors();
			backup();
			turnleft();
		}
	}
}
