#pragma config(Sensor, S1,     leftColor,      sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S2,     rightColor,     sensorEV3_Color, modeEV3Color_Color)
#pragma config(Sensor, S4,     sonarSensor,    sensorEV3_Ultrasonic)
#pragma config(Motor,  motorB,          leftMotor,     tmotorEV3_Large, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motorC,          rightMotor,    tmotorEV3_Large, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int distanceList[6];
void rsMotors(){//Reset Motor Encoders
	sleep(200);
	resetMotorEncoder(motorB);
	resetMotorEncoder(motorC);
}
void STP(){
	motor[motorB] = 0;
	motor[motorC] = 0;
	sleep(1000);
}

void forward(int sped){//Moves forward on a condition until it sees black
	motor[motorB] = sped;
	motor[motorC] = sped;
}
void setDist(int dist){
	dist == getMotorEncoder(motorB)
	setMotorTarget(motorB, -dist, 15);
	setMotorTarget(motorC, -dist, 15);
	waitUntilMotorStop(motorB);
}
task display()
{

}
task EBRAKE(){
	if(SensorValue[S4] < 20){
		stopAllTasks();
	}
}
void reverse(){

}
task main(){
	rsMotors();
	startTask(display);
	startTask(EBRAKE);
	for(int i=0; i<6; i++)
	{
		sleep(200);
		while(getColorName(S1) == colorWhite){
			forward(15);
		}
	STP();
	distanceList[i]= getMotorEncoder(motorB);
	}
}
